name: Run Telugu Scraper Twice Daily

on:
  schedule:
    - cron: '0 3,15 * * *'  # Runs at 08:30 AM IST and 08:30 PM IST
  workflow_dispatch:        # Allow manual trigger too
permissions:
  contents: write
jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install youtube-transcript-api googletrans==4.0.0-rc1
          pip install pytube deep-translator
          pip install playwright
          pip install nest_asyncio 
          pip install beautifulsoup4 
          pip install google-auth 
          pip install google-auth-oauthlib 
          pip install gspread
          playwright install

      - name: Run scraper script
        run: python news.py  # Replace with your script's filename
      - name: Commit output
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "srinivasraaj"
          git config user.email "srinivasraaj@github.com"
          git add output.txt
          git commit -m "Update output.txt" || echo "No changes to commit"
          git remote set-url origin https://srinivasraaj:${GH_PAT}@github.com/srinivasraaj/news.git
          git push
