name: Run Telugu Scraper Twice Daily

on:
  schedule:
    - cron: '0 3,15 * * *'  # Runs at 08:30 AM IST and 08:30 PM IST
  workflow_dispatch:        # Allow manual trigger too

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install youtube-transcript-api googletrans==4.0.0-rc1
          pip install pytube deep-translator
          pip install playwright
          playwright install

      - name: Run scraper script
        run: python news.py  # Replace with your script's filename
